# Generated by Django 2.2.5 on 2019-11-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20191113_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='user_required',
        ),
    ]
