# Generated by Django 2.2.5 on 2019-11-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productfile_name_cus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfile',
            old_name='name_cus',
            new_name='name',
        ),
    ]
